### ISSUE TITLE
Improve Why Zsh over bash

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#10]
The `WHY_ZSH.md` file

**Comment by nelsonic** [comment]
Also: https://fishshell.com 😉

**Comment by samhstn** [comment]
Ooh, haven't seen that before, I'll give it a go

**Comment by samhstn** [comment]
So after playing around with fish it for a little bit, I'm moving back to zsh.

Although, I think it could definitely be a good shell choice for the next FAC, as it does set it's self up nicely out of the box and have a really pleasant interface to work with.

I don't really care for many of it's advantages such as nice configuration interfaces, nice colours and stuff out of the box. To be honest, I prefer when things don't have that.

My biggest turn off for fish is the compatibility issues and knowing that the shell I write may not be able to be used others unless their using fish.

**Comment by nelsonic** [comment]
@shouston3 familiarity dictates most tech decisions ... 😉 
but agree on the compatibility point. 👍

**Comment by nelsonic** [comment]
No need to _re-open_. ZSH works well for most people. 👍 
(_unless you closed unintentionally and still want to add to your `.md` file..._)

**Comment by samhstn** [comment]
This issue was opened to address the `tbd` point in [`WHY_ZSH.md`](https://github.com/shouston3/My-Config/blob/master/WHY_ZSH.md), but I forgot that when I closed the issue.
