### ISSUE TITLE
Markdown previewer

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#22]
I've had a play with [`grip`](https://github.com/joeyespo/grip), works very well and is github flavoured

May add a note on this in a while unless another is _much_ better, or if there is a good reason to not use it

**Comment by nelsonic** [comment]
@shouston3 cool. is it _fast_? (_how big was the `.md` file you tested with...?_)

**Comment by samhstn** [comment]
@nelsonic Just tested it with the `README.md` from [dwyl/learn-tdd](https://github.com/dwyl/learn-tdd). The preview updates on save pretty much immediately. So very fast.

**Comment by nelsonic** [comment]
@shouston3 that's _really_ good news! 🎉 
I look forward to seeing a demo of your `.md` editor. 😉

**Comment by karinakozarova** [comment]
Check out haroopad: http://pad.haroopress.com.
I'm currently using it and it feels really good indeed.

**Comment by samhstn** [comment]
See #33
