### ISSUE TITLE
Gitter link broken

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#43]
The gitter link in `README.md` is broken, linking to https://gitter.im/shouston3, should be https://gitter.im/samhstn

**Comment by nelsonic** [comment]
@samhstn the link on your profile is also: https://shouston3.github.io/
![image](https://user-images.githubusercontent.com/194400/50899277-83cca980-1409-11e9-964f-6cb2d4c7fbbc.png)

Which is a 404:
![image](https://user-images.githubusercontent.com/194400/50899291-91822f00-1409-11e9-812e-fb358b5c86d6.png)
Not that I'm "stalking" you or anything ... 😉 
But if you're in a "fixing things" mood ... 🔧 
Hope your day is going well BTW. ☀️

**Comment by samhstn** [comment]
Thanks for spotting @nelsonic! Yep, I'll look at fixing that soon (https://github.com/samhstn/samhstn/issues/1), I've let that typo it go for too long now

Everything's going well over here, can't complain 👍 Hope everything's good for you out in Portugal ☀️ - v jealous btw
