### ISSUE TITLE
Replace WHY_*.md with WORKFLOW.md

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#56]
Describing how I like to work would be better than trying to explain why I use particular tools.

A single file summarising how I like to work would be better than partitioning how I work into different places - this is important as I use tools together and don't use my text editor, the terminal or the browser by themselves, so why would I talk about them in isolation.

I should write this up so that when I am working intensely on a project, I have thought out workflow rules to follow as well as general principles to apply when I use new tooling.

Thoughts to address:

##### Automate as much as possible.
+ Record your answers so you will only improve on your how you think and you won't have to re answer/rethink it.
+ Reviewing code mistakes which can be caught by a linter is a waste of time - automation is the answer.
+ Fixing typos/addressing simple grammar mistakes is a waste of time, there is tooling for this.
+ Testing - what to test - thoughts on coverage.
##### Importance of documentation
How to write documentation (https://hackernoon.com/why-senior-devs-write-dumb-code-and-how-to-spot-a-junior-from-a-mile-away-27fa263b101a)
Nothing should ever need to be explained.
##### Workflow in the terminal
(Importance of a linter, but not to lint on save. Why I don't like the noise of a directory tree on my screen? Thoughts on autocompletion. Thoughts on syntax highlighting).
##### Importance of not rushing
(https://github.com/elm/projects/blob/master/roadmap.md#what-is-the-timeline)

**Comment by nelsonic** [comment]
@samhstn a mark of a craftsman/craftsperson is _deliberately_ considering both their tools and workflow. 
While I don't even _pretend_ to be as good at writing code as some of the great devs on this list [git.io/top](https://git.io/top),
one thing I learned _early_ on is that writing beginner-friendly code & docs is the difference between success and failure in Open Source and thus in a "career" as a programmer. 
I _often_ see people trying to use _terse_ code when more _verbose_ (_i.e. readable_) code is _much_ more maintainable. A _clear_ sign of the _noviceness_ is thinking that code is only for the machine to run ... 
https://stackoverflow.com/questions/522828/is-code-for-computers-or-for-people

All of the topics you have listed are worthy of individual essays with examples.
I look forward to reading further. 👀
