### ISSUE TITLE
Postgres.app

### ISSUE THREAD

**Issue by ivan-unfolds** [samhstn/my-config#6]
Apparently Postgres.app is the most painless set up of postgres for mac users.

**Comment by samhstn** [comment]
Having briefly looked in to it, I don't agree

I agree that in general it is the most painless way to set up postgres, but not for macOS users

If I start using a Postgres gui, then I will reconsider.

Given we already have brew, it can be done with literally: `brew install postgres`.

Thanks for bringing up this as an alternative though
