### ISSUE TITLE
Escape/Caps lock

### ISSUE THREAD

**Issue by otajor** [samhstn/my-config#7]
Do you get out of insert mode using the actual escape key?
It's way too far away! Use caps lock :) :)

> Change Caps Lock key to "No Action"

should be 

> Change Caps Lock key to "Escape"

**Comment by samhstn** [comment]
I'm using another tool called [seil](https://pqrs.org/osx/karabiner/seil.html.en) to manage my key remappings

@otajor Check out step 3 of [this](https://pqrs.org/osx/karabiner/seil.html.en#noaction)

**Comment by otajor** [comment]
Ahh I see so that's to stop the delay. But you're not remapping it to another key?

**Comment by samhstn** [comment]
Seil is the tool to remap your keys

**Comment by otajor** [comment]
I thought karabiner was for remapping your keys.

Just trying to work out what you're doing with caps lock here. So the system preferences stuff ('No action') just gets rid of the annoying delay.

> Click change caps lock key and set input key code: 59

This seems to remap caps lock to left ctrl? But you've already remapped that to escape using karabiner :S

> General > Change Control_L Key(Left Control) dropdown Tick: Control_L to Control_L (+ When you type Control_L only, send Escape)

**Comment by samhstn** [comment]
So, you remap your caps lock to CTRL_L using seil (karabiner will say to use seil for the caps lock key remapping).

Then using karabiner you configure that when you press CTRL_L you will also "send" the ESC key.

So now whenever you press the caps lock key you will always execute both: "send ESC" and the normal CTRL functionality.

I hope that's clear, let me know if it's not
