### ISSUE TITLE
Fix pesky ASCII 160 (non-breaking space) character in markdown

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#72]
Due to using the wrong space character (don't know how this initially happened), markdown headers are not displaying or linking correctly

![Screenshot 2019-03-09 at 17 18 12](https://user-images.githubusercontent.com/15983736/54074833-6ee88700-428f-11e9-8f71-9c6644b73228.png)

These should be changed for a unicode ASCII 32 space character which will render correctly

![Screenshot 2019-03-09 at 17 20 08](https://user-images.githubusercontent.com/15983736/54074847-9a6b7180-428f-11e9-856f-f30f88267777.png)

**Comment by nelsonic** [comment]
I'd _love_ to understand why `ASCII 160` gets inserted instead of `ASCII 32` _ever_ 
in the context of hitting the space bar in a text editor. 🤔

**Comment by samhstn** [comment]
So, I realised how this happens.
A `#` symbol is typed with `Alt + 3`
If you keep the `Alt` key pressed when you type `<space>` it will result in an `ASCII 160` char not an `ASCII 32` char

**Comment by nelsonic** [comment]
Great detective work @samhstn 💡
