### ISSUE TITLE
Leader

### ISSUE THREAD

**Issue by otajor** [samhstn/my-config#8]
[`let mapleader = "\<space>"`](https://github.com/shouston3/My-Config/blob/master/.vimrc#L38)

Does this mean that you are using space as your leader key? Or is it backslash+space?

**Comment by samhstn** [comment]
@otajor It's just the space key. backslash+space would be too long.
See the answer [here](http://stackoverflow.com/questions/446269/can-i-use-space-as-mapleader-in-vim)

**Comment by otajor** [comment]
Cool, interesting. I'm not sure what to use for leader atm - are there any downsides to using space as leader?

**Comment by samhstn** [comment]
The default use is exactly the same as the "l" and `<right>` key (see `vim -c ':help <space>'`), so I think pretty much no downsides.
