### ISSUE TITLE
Address why vim is better

### ISSUE THREAD

**Issue by samhstn** [samhstn/my-config#9]
In the `WHY_VIM.md` file

**Comment by nelsonic** [comment]
@shouston3 have you seen: https://vimgifs.com ?

**Comment by samhstn** [comment]
@nelsonic Amazing, hadn't seen that before, thank you, spent a while noting down some cool ones, but it made me realise theres loads more to learn

[![gitter badge](https://img.shields.io/badge/foundersandcoders-vim-brightgreen.svg)](https://gitter.im/foundersandcoders/vim)

**Comment by nelsonic** [comment]
@shouston3 if you want to make put up a "_barrier to entry_", 
"_force_" people to learn/use Vim.
(_I'm a huge fan. but when I used to use it while teaching people ...
people often got "confused"..._) 😞
